---
extends: default

ignore: |
  volumes

rules:
  document-end:
    level: warning
  empty-values:
    level: warning
  indentation:
    spaces: 2
    check-multi-line-strings: false
  line-length:
    max: 120
  octal-values: enable
  quoted-strings:
    quote-type: single
    required: only-when-needed
    level: warning
...
