---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whoami
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: whoami
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/whoami
...
