---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-db
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wordpress-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/wordpress-db
...
