name: Test
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: |
          pip install yamllint
          yamllint .

      - name: Setup kubernetes cluster
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.4.4 bash
          curl -s https://fluxcd.io/install.sh | FLUX_VERSION=0.34.0 bash
          ./setup.sh

      - name: Test whoami app
        run: |
          curl --fail --silent "http://whoami.127.0.0.1.nip.io:8080"
          curl --fail --silent --insecure "https://whoami.127.0.0.1.nip.io:8443"
