---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - wordpress-db
  - external-secret.yaml
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
...
