---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - db
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
secretGenerator:
  - name: wordpress
    envs:
      - .env.example
...
